workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - keystore_reference
      groups:
        - google_play
      vars:
        PACKAGE_NAME: "com.allensmart.driver"
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Build APK with Flutter
        script: | 
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - prakaldathanvelan@gmail.com
        notify:
          success: true
          failure: true
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  ios-workflow:
    name: iOS Workflow
    max_build_duration: 120
    instance_type: mac_mini_m1
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.allensmart.driver
      vars:
        APP_STORE_APPLE_ID: 6757453404
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Initialize keychain for code signing
        script: | 
          keychain initialize
      - name: Set up code signing settings on Xcode project
        script: | 
          xcode-project use-profiles
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Install pods
        script: | 
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter analyze
        script: | 
          flutter analyze
      - name: Flutter unit tests
        script: | 
          flutter test
        ignore_failure: true
      - name: Build ipa for distribution
        script: | 
          # Get the latest build number from TestFlight and increment it
          LATEST_BUILD=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID" || echo "0")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          echo "Latest TestFlight build: $LATEST_BUILD"
          echo "New build number: $BUILD_NUMBER"
          
          flutter build ipa --release \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - prakaldathanvelan@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - App Store Connect Users
        submit_to_app_store: false

  web-workflow:
    name: Web Workflow
    max_build_duration: 60
    instance_type: linux_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build web
        script: | 
          flutter build web --release --web-renderer canvaskit
    artifacts:
      - build/web/**
    publishing:
      email:
        recipients:
          - prakaldathanvelan@gmail.com
        notify:
          success: true
          failure: true

  windows-workflow:
    name: Windows Workflow
    max_build_duration: 60
    instance_type: windows_x2
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter packages
        script: | 
          flutter packages pub get
      - name: Build Windows
        script: | 
          flutter build windows --release
    artifacts:
      - build/windows/**/*.msix
      - build/windows/**/*.exe
    publishing:
      email:
        recipients:
          - prakaldathanvelan@gmail.com
        notify:
          success: true
          failure: true
